#include <Arduino.h>
#include <bits/stdc++.h> 
#include <stdlib.h> 
#include <unistd.h> 
#include <string.h> 
#include <sys/types.h> 
#include <sys/socket.h> 
#include <arpa/inet.h> 
#include <netinet/in.h> 

// denotes state of handshake
enum HandshakeState {
    CLOSED,         // opening communication...
    LISTEN,         // ...
    SYN_SENT,       // ...
    SYN_RCVD,       // ...
    ESTABLISHED,    // established communication...
    FIN_WAIT_1,     // ...
    FIN_WAIT_2,     // ...
    CLOSING,        // ...
    TIME_WAIT,      // ...
    CLOSE_WAIT,     // ...
    LAST_ACK,       // ...
    CLOSED          // ...
};

// denotes the received flags from remote or action taken by local
enum EventTCP {
    Send,           // local action...
    Close,          // ...
    SYN,            // received flags...
    ACK,            // ...
    SYN_ACK,        // ...
    FIN,            // ...
    FIN_ACK         // ...
}